sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000 JVVMAJOR=8 TMVMAJOR=8 TMVERSION=8.5.24
  - ARCH=armhf  PUID=1001 PGID=1001 JVVMAJOR=8 TMVMAJOR=8 TMVERSION=8.5.24
  global:
  - secure: dCt4rYXKQje9ds5ARwgmO09OcW0UIBnx/wOxqmUDTyVsH/evQvlG4Zlb70RmkbcDkZtu/EqFOpnvyRoFOvAfnxhTH0Pl16FczhIoEeHPsQrNHqIUXqfxNrMjQXdCsi8YJzejyjOxYvxgi8T5ebaHp0lMWERd1n8QlYSH02qCUewhA18r8T96ORt0YVzaWLytMJfrb2W6ej0YkPe0yw6aEnBCwgvckRvAiQOp80R1uAIdwrHAX1Xx2zu2C+/xDrkvWdUlkFy4+bNcXwrEaHHAXDnZOx/iMvr+q8KQScV1SsksVd4HXsdLx1zUn0lk8AP/7u/yRSf/xLjXjl9G4IJMXt8FT0ThMcgSEZkBNGUZ/VJxD7M7+bC3ZR9EHmUZgRf+Z/an69JwRwLkTaa0g4gGPRVKZeGN6tRgwVI3TiYMgS2BaulE+YPj+9+ATAA//I+ZBpi7i2XP6HEgpctt5nKqcNrfMmtKSwTpSI9HDCf1pyCzFOUesbMHmXbUCuwcWHgK2x6tINIkpwYjtpkGKpohr63q73GKdX8TAI3LgfobmiF/LRnKt1vpsb6Cj36DoZrcuLWTEX5N9YDZJRrg4ZCjKlgXKXGrdvdX6F2O+mFd4pG1FqiGG1kJnEuymFql0yHjd53i51CM8cVy20//V3Z6VB272s8hB9c/pIsHxLDWuIU=
  - secure: lV38PrVhRhrehGUUL3C2Lis6nlK5MeNTmG2/qaOmWlHCkzhBHLH/WYQA+ES8wRwRsK42yf5A2K91FOO5dRsNqllqvAb47UuMSJgvLp99jRrufC28TF9ZFnumPoJJae7/K3GTZq64/zJTFtJLeEOnw0Ng8srqRBz8M6OoUaA+WuL3oLU/yaXd38YbCIjo1dXST/xv582dncT5CB/wnHu3TS7FtG6qwNKNcxKD96z8y1xhN4qXlg/0HUuMvbbXIYg6+ZrUkwTjbdPbuL7tzKV6Oz0sjFFwLc4Q/DEyNlk891J0ZDc8Uk36x4Vu3cF6VGRicU44iWw3dk1ZU6LLH2O77LXWGnJ775TGmJ2UTrBkzuEmFpfjy4B2gRlU5YAKK58Fc82efyQMEWQH8bhK1c8KsfamuK4rS700lJZWANDDcmL1/2HmRErhFZd2zHkj64ujaKGpfIXCJdjDvZHsgC/zSOJCYhnLWQxO5D3tlgAKJWZwNsJOS2znzMk9wqsYemaearV/GgOgZb6Q5LCQpJ9ujDu4orAGztRp9KCq6V27xersQlKuhKRn9ReW8gsRquzWWvgt8n3YwxOdUy8kjK8ZBAAhz/FMZQcqDZomXY1xyT2Ftk6bAs69g8m5bGoqTrPnkE3YljXx+J/sWYh++dwYYBdtiwihcO1GS8ocROEalwg=
install: true
before_script:
- docker --version
- make --version
script:
  - make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} JVVMAJOR=${JVVMAJOR} TMVMAJOR=${TMVMAJOR} TMVERSION=${TMVERSION} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
